version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'cd:99:74:94:17:13:5c:95:a9:13:e5:a0:e1:d1:16:3a'
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build
      - run:
          command: |
            git config --global user.email $GH_EMAIL
            git config --global user.name $GH_NAME
            yarn deploy
